- hosts: database
  gather_facts: False
  become: True
  roles:
    - database

- hosts: api
  gather_facts: False
  become: True
  roles:
    - api
  vars:
    almanach_mongodb_url: mongodb://almanach:almanach@172.27.54.98:27017/almanach

- hosts: collector
  gather_facts: False
  become: True
  roles:
    - collector
  vars:
    almanach_mongodb_url: mongodb://almanach:almanach@172.27.54.98:27017/almanach
